#!/bin/bash

alreadyExists () {
    if [ -e "$1" ]; then
        return 0
    else
        return 1
    fi
}

isInstalled () {
    command -v $1 >/dev/null 2>&1 && return 0 || return 1
}

checkInstallStatus () {
    isInstalled $1 && clr_bold clr_green "Successfully installed $1!" ||
        (clr_bold clr_red "Failed to install $1!" && exit 1)
}

